export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST'
export const TEST_LIST_SUCCES = 'TEST_LIST_SUCCES'
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL'


export const TEST_ADD_REQUEST = 'TEST_ADD_REQUEST'
export const TEST_ADD_SUCCES = 'TEST_ADD_SUCCES'
export const TEST_ADD_FAIL = 'TEST_ADD_FAIL'